runtime: python310

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10

env_variables:
  # TODO: Update these values when deploying to production
  RUBE_BASE_URL: "https://api.rube.app"
  RUBE_API_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ1c2VyXzAxS0JHWEgxUVRBTTdXWEYyVkhIUFoxS0paIiwib3JnSWQiOiJvcmdfMDFLQkdYSFJTRlZFQk5XRjBYQk5RU0RIUTkiLCJpYXQiOjE3NjQ3MjY0MzZ9.idSTo6x7YbVRBFqR-WZJgd4JT9NYGdWVfVB6xzQrlkY"

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
