runtime: python310

instance_class: F1

automatic_scaling:
  # Scale to zero when idle (cost optimization)
  min_instances: 0
  # Low limit to prevent unexpected costs
  max_instances: 3
  # Scale up when requests are waiting
  target_concurrent_requests: 5

env_variables:
  # Application configuration
  LOG_LEVEL: "INFO"

# Optimized for F1 instance (256MB RAM)
# - Single worker to minimize memory usage
# - Timeout to prevent hanging requests
# - Graceful timeout for proper shutdown
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 30 --graceful-timeout 10 app.main:app
